### ISSUE TITLE
ClassCastException on Android 6.0.1

### ISSUE THREAD

**Issue by IRMobydick** [michaelprimez/searchablespinner#5] opened 2017-03-05 11:30 UTC
`java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams`

SearchableSpinner.java - Line 368
LinearLayout.LayoutParams listLayoutParams = (LinearLayout.LayoutParams) mSpinnerListView.getLayoutParams();

**Comment by michaelprimez** [comment] 2017-03-05 12:21
Hi @IRMobydick please try version 1.0.4, i am not sure if it solve the problem because it's not reproducible. In any case please tell me your results. 
Thanks

**Comment by IRMobydick** [comment] 2017-03-07 07:21
Well, first of I'm sorry for wrong address, The problem goes to this section of code:

`mRevealItem.addView(mCurrSelectedView.getView());`
When user select view from list and SearchableSpinner try add it to `RevealItem` view.

and Yes, it happens on some devices, in my case Samsung Galaxy Note 5!
this work great on some other devices like HTC and...

**Comment by michaelprimez** [comment] 2017-03-07 08:20
Thanks @IRMobydick i'll check it, the exception is the same i guess.

**Comment by IRMobydick** [comment] 2017-03-07 10:15
maybe helpful, crash log:

    java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
    at android.widget.ListView.onInitializeAccessibilityNodeInfoForItem(ListView.java:4154)
    at android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo(AbsListView.java:3011)
    at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6619)
    at android.view.View.createAccessibilityNodeInfoInternal(View.java:6580)
    at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:23712)
    at android.view.View.createAccessibilityNodeInfo(View.java:6563)
    at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
    at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
    at android.view.View.onInitializeAccessibilityEventInternal(View.java:6517)
    at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:23624)
    at android.view.View.onInitializeAccessibilityEvent(View.java:6503)
    at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6364)
    at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:23563)
    at android.view.View.sendAccessibilityEventUnchecked(View.java:6347)
    at android.view.View.sendAccessibilityEventInternal(View.java:6326)
    at android.view.View$AccessibilityDelegate.sendAccessibilityEvent(View.java:23521)
    at android.view.View.sendAccessibilityEvent(View.java:6291)
    at android.view.View.performClick(View.java:5703)
    at android.view.View$PerformClick.run(View.java:22534)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by michaelprimez** [comment] 2017-03-12 19:55
Hi @IRMobydick 
I've managed to reproduce the problem and the new version 1.0.5 is dealing with it. I guess! Please once again try the new version and tell me if something is wrong otherwise you just close the issue.
Thanks

**Comment by IRMobydick** [comment] 2017-03-12 20:47
Okay bro, i'll check it and send feedback to you 👍

**Closed** 2017-03-18 08:50 UTC

**Comment by V3RT1AG0** [comment] 2018-01-31 04:20
I am getting the same error in android 6.0 for version 1.0.9 

`Fatal Exception: java.lang.ClassCastException
android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
keyboard_arrow_up
arrow_right
android.widget.ListView.onInitializeAccessibilityNodeInfoForItem (ListView.java:3950)
android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo (AbsListView.java:2410)
android.view.View.onInitializeAccessibilityNodeInfo (View.java:6093)
android.view.View.createAccessibilityNodeInfoInternal (View.java:6054)
android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo (View.java:22327)
android.view.View.createAccessibilityNodeInfo (View.java:6037)
android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:145)
android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:119)
android.view.View.onInitializeAccessibilityEventInternal (View.java:5991)
android.widget.TextView.onInitializeAccessibilityEventInternal (TextView.java:8914)
android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent (View.java:22239)
android.view.View.onInitializeAccessibilityEvent (View.java:5977)
android.view.View.sendAccessibilityEventUncheckedInternal (View.java:5844)
android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked (View.java:22178)
android.view.View.sendAccessibilityEventUnchecked (View.java:5827)
android.view.View.sendAccessibilityEventInternal (View.java:5806)
android.widget.TextView.sendAccessibilityEventInternal (TextView.java:9114)
android.view.View$AccessibilityDelegate.sendAccessibilityEvent (View.java:22136)
android.view.View.sendAccessibilityEvent (View.java:5771)
android.widget.AdapterView.performItemClick (AdapterView.java:317)
android.widget.AbsListView.performItemClick (AbsListView.java:1145)
android.widget.AbsListView$PerformClick.run (AbsListView.java:3081)
android.widget.AbsListView$3.run (AbsListView.java:3947)
android.os.Handler.handleCallback (Handler.java:742)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:157)
android.app.ActivityThread.main (ActivityThread.java:5555)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:745)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:635)`

**Comment by mehranahmadifar** [comment] 2018-11-11 20:07
> I am getting the same error in android 6.0 for version 1.0.9
> 
> `Fatal Exception: java.lang.ClassCastException android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams keyboard_arrow_up arrow_right android.widget.ListView.onInitializeAccessibilityNodeInfoForItem (ListView.java:3950) android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo (AbsListView.java:2410) android.view.View.onInitializeAccessibilityNodeInfo (View.java:6093) android.view.View.createAccessibilityNodeInfoInternal (View.java:6054) android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo (View.java:22327) android.view.View.createAccessibilityNodeInfo (View.java:6037) android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:145) android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:119) android.view.View.onInitializeAccessibilityEventInternal (View.java:5991) android.widget.TextView.onInitializeAccessibilityEventInternal (TextView.java:8914) android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent (View.java:22239) android.view.View.onInitializeAccessibilityEvent (View.java:5977) android.view.View.sendAccessibilityEventUncheckedInternal (View.java:5844) android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked (View.java:22178) android.view.View.sendAccessibilityEventUnchecked (View.java:5827) android.view.View.sendAccessibilityEventInternal (View.java:5806) android.widget.TextView.sendAccessibilityEventInternal (TextView.java:9114) android.view.View$AccessibilityDelegate.sendAccessibilityEvent (View.java:22136) android.view.View.sendAccessibilityEvent (View.java:5771) android.widget.AdapterView.performItemClick (AdapterView.java:317) android.widget.AbsListView.performItemClick (AbsListView.java:1145) android.widget.AbsListView$PerformClick.run (AbsListView.java:3081) android.widget.AbsListView$3.run (AbsListView.java:3947) android.os.Handler.handleCallback (Handler.java:742) android.os.Handler.dispatchMessage (Handler.java:95) android.os.Looper.loop (Looper.java:157) android.app.ActivityThread.main (ActivityThread.java:5555) java.lang.reflect.Method.invoke (Method.java) com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:745) com.android.internal.os.ZygoteInit.main (ZygoteInit.java:635)`
> 
> @IRMobydick were you able to solve the problem?

i have same problem on touch item in list! can you fix this?

**Comment by mehranahmadifar** [comment] 2018-11-12 13:32
> > I am getting the same error in android 6.0 for version 1.0.9
> > `Fatal Exception: java.lang.ClassCastException android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams keyboard_arrow_up arrow_right android.widget.ListView.onInitializeAccessibilityNodeInfoForItem (ListView.java:3950) android.widget.AbsListView$ListItemAccessibilityDelegate.onInitializeAccessibilityNodeInfo (AbsListView.java:2410) android.view.View.onInitializeAccessibilityNodeInfo (View.java:6093) android.view.View.createAccessibilityNodeInfoInternal (View.java:6054) android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo (View.java:22327) android.view.View.createAccessibilityNodeInfo (View.java:6037) android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:145) android.view.accessibility.AccessibilityRecord.setSource (AccessibilityRecord.java:119) android.view.View.onInitializeAccessibilityEventInternal (View.java:5991) android.widget.TextView.onInitializeAccessibilityEventInternal (TextView.java:8914) android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent (View.java:22239) android.view.View.onInitializeAccessibilityEvent (View.java:5977) android.view.View.sendAccessibilityEventUncheckedInternal (View.java:5844) android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked (View.java:22178) android.view.View.sendAccessibilityEventUnchecked (View.java:5827) android.view.View.sendAccessibilityEventInternal (View.java:5806) android.widget.TextView.sendAccessibilityEventInternal (TextView.java:9114) android.view.View$AccessibilityDelegate.sendAccessibilityEvent (View.java:22136) android.view.View.sendAccessibilityEvent (View.java:5771) android.widget.AdapterView.performItemClick (AdapterView.java:317) android.widget.AbsListView.performItemClick (AbsListView.java:1145) android.widget.AbsListView$PerformClick.run (AbsListView.java:3081) android.widget.AbsListView$3.run (AbsListView.java:3947) android.os.Handler.handleCallback (Handler.java:742) android.os.Handler.dispatchMessage (Handler.java:95) android.os.Looper.loop (Looper.java:157) android.app.ActivityThread.main (ActivityThread.java:5555) java.lang.reflect.Method.invoke (Method.java) com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:745) com.android.internal.os.ZygoteInit.main (ZygoteInit.java:635)`
> > @IRMobydick were you able to solve the problem?
> 
> i have same problem on touch item in list! can you fix this?

i Fix this with Edit Code at SearchableSpinner.java :

                //mRevealItem.removeAllViews();
                mSpinnerListView.removeViewInLayout(mCurrSelectedView.getView());

                ((TextView) mRevealItem.getChildAt(0))
                        .setText(((AppCompatCheckedTextView) 
                                mCurrSelectedView.getView()).getLayout().getText().toString());
                ((TextView) mRevealItem.getChildAt(0)).setTextColor(Color.BLACK);

                //mRevealItem.addView(mCurrSelectedView.getView());
                ((BaseAdapter) mSpinnerListView.getAdapter()).notifyDataSetChanged();
